### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by eag-microbio** [karkman/gff_parser#10]
Hello! I'm brand new to using anvio... I have been trying to use your importing prokka annotations into anvio script (https://merenlab.org/2017/05/18/working-with-prokka).

I run this script: 
python gff_parser.py PROKKA_JKS002657/PROKKA.gff --gene-calls JKS002657gene_calls.txt --annotation JKS002657gene_annot.txt 

and get this error: 
 File "gff_parser.py", line 124
    print(f"Done. All {total_num_features} have been processed succesfully. There were {call_types['CDS']} coding "
                                                                                                                  ^
SyntaxError: invalid syntax

It  does not make the gene call or annotation files. 

I've gone through and simplified my contigs names. I'm not sure what else I should be checking... 
I have anvio v7. 

Thank you!

**Comment by karkman** [comment]
Hi,
Which version of python you’re using? The script works only with python3.  

If this is not the problem and this is a bug, unfortunately I won’t be able to fix this before early August. 

Best regards
Antti

**Comment by eag-microbio** [comment]
Hi Antti,
Thank you for the fast reply! I realize we are using python 2 7.15.

Thank you!
Emily
