### ISSUE TITLE
gff parser works well but generated files clash with anvi'o

### ISSUE THREAD

**Issue by RMasteling** [karkman/gff_parser#7]
After smoothly running gff_parser.py I get the following errors/messages when running anvi'o

when using ```anvi-gen-contigs-database```  I get a config error: "There are more fields in the file 'gene_calls.txt' than the expected fields. Anvi'o is telling you about this because get_TAB_delimited_file_as dictionary functions is called with 'only_expected_fields` flag turned on.

When running ```anvi-import-functions``` the config error reads: A value for 'genes_are_called' does not seem to be set in table 'self'

**Comment by karkman** [comment]
Hi,
Not exactly sure what's wrong, but let's start with the basics. 
Do you have thew latest version of gff_parser.py? And what is the version of your Anvi'o?
It should work with Anvi'o v. 6.2. -->

Best, 
Antti

**Comment by stephlei** [comment]
I actually was just running into this error as well. I made sure I was running anvio 6.2. However I was able to discern from the [Anvio website](https://merenlab.org/software/anvio/help/main/artifacts/external-gene-calls/) that the external calls that have call_type only work on the Anvio AFTER 6.2. I went through and removed the code involving call_type from my local version and that seemed to work on fixing the error.

**Comment by karkman** [comment]
Hi Stephanie, 
thank you for the information. I'll take a look.
Maybe @meren has some suggestions? 

Best,
Antti

**Comment by meren** [comment]
Hey @stephlei! I am trying to catch up with the discussion. From your last message I get the impression that the problem is solved, is it true?

I think I had edited the gff_parser code to make sure it can work with both `v6.2` and the `main` branch, but perhaps I'm wrong.

What is the current situation? Are there some example files you can share so I can reproduce the problem?

**Comment by stephlei** [comment]
@meren Yep I was able to fix it by editing the gff_parser itself. Here are some of the files that I was using.
[exampleFiles.zip](https://github.com/karkman/gff_parser/files/5690849/exampleFiles.zip)
